### ISSUE TITLE
update to use alpheios-alignment__disabled for translation visibility

### ISSUE THREAD

**Issue by balmas** [alpheios-project/enhanced-texts-v1#2]
for alpheios-project/components#152 I changed the way the code detects whether or not the aligned text is visible on the page. Previously I used a "visible" class to indicate it was visible, this should be switched to use the "alpheios-alignment__disabled" class if it is not.

**Comment by balmas** [comment]
sample changes for this are in the feature-alignment branch

**Comment by irina060981** [comment]
merged and closed
https://github.com/alpheios-project/components/pull/159
